### ISSUE TITLE
visiblePartY == 'bottom' fired at the wrong time

### ISSUE THREAD

**Issue by graemearg** [protonet/jquery.inview#2]
<p>visiblePartY is fired when the top of the element moves out of the viewport, not when the bottom of the element moves into the viewport, making it impossible to detect when the bottom of an element has appeared. Produced in FF3.6, Saf5, Chrome9 (Not tested IE, Opera). Jquery1.4.2.</p>
<p>Example, based on the simple example from README:</p>
<pre>
<code>
&lt;div style="min-height:2000px;border:1px red solid;"&gt;&lt;/div&gt;
&lt;script type="text/javascript"&gt;
$('div').bind('inview', function(event, isInView, visiblePartX, visiblePartY) {
 if (isInView) {
  // element is now visible in the viewport
  if (visiblePartY == 'top') {
   // top part of element is visible
   console.log('Can see the top.');
  } else if (visiblePartY == 'bottom') {
   // bottom part of element is visible
   console.log('Can see the bottom.');
  } else {
   // whole part of element is visible
  }
 } else {
  // element has gone out of viewport
 }
});
&lt;/script&gt;
</code>
</pre>

**Comment by qborreda** [comment]
+1

**Comment by myurtsev** [comment]
+1

**Comment by tiff** [comment]
not supporting ``visiblePartX`` anymore in the recent version. I'd like to keep this lib as simple as possible.
