### ISSUE TITLE
Not working on multiple elements on jQuery 2.x

### ISSUE THREAD

**Issue by albertogasparin** [protonet/jquery.inview#26]
jQuery cache property has been changed. Now is `jQuery.expando + Math.random()`.
http://stackoverflow.com/questions/20979302/how-does-jquery-2-x-uniquely-identify-an-element-in-data

So, on line 12:

```
data.guid + "-" + this[expando]
```

returns `[int]-undefined` if you are binding multiple elements in one call.

**Comment by topazkane** [comment]
Any progress on this issue?

**Comment by MorrisDa** [comment]
You can do a simple workaround for fixing this by calling the bind method multiple times 

```
$('.selector').each(function() {
 $(this).bind('inview', function(event, isInView, visiblePartX, visiblePartY) {});
})
```

This worked well for me @topazkane

**Comment by tiff** [comment]
this has been fixed with https://github.com/protonet/jquery.inview/commit/be2769f8fc9b22587df2bc293b8dd94ef26e0888
