### ISSUE TITLE
Wrong behaviour after page resize

### ISSUE THREAD

**Issue by Decadence** [protonet/jquery.inview#38]
Hello.
This plugin works great. But I noticed one issue: after I resize page, event handler get wrong params. Element that is now in viewport gets isInView == false, and element that is under the viewport gets isInView == true. That's why "visible" class is removed and element in viewport just disappears.
After page reload with this page size it works ok.

I use this code:

``` javascript
$('div.section').on('inview', function(event, isInView, visiblePartX, visiblePartY) {
        var $this = $(this);

        if (isInView) {
            $this.addClass("visible");
        }
        else{
            $this.removeClass("visible");
        }
    });
```

Webkit based browsers works fine, problem in Opera 12, latest Firefox and IE.
Also I tried disable media-queries with no luck.

Or I have to rebind event handlers after each resize?

Screenshot - http://s7.hostingkartinok.com/uploads/images/2014/12/2e41d91a3098988412bd5634796e8a33.png

**Comment by exside** [comment]
Have similar problem, when I have Firebug open in Firefox inview always returns false, no matter if en element is inview or not, so elements just do not display/behave as they should which is misleading (e.g. indicating bugs where there are none =D)

**Comment by sadikyalcin** [comment]
Replicated on Chrome v 75.0.3770.100 (Official Build) (64-bit). I have a carousel of iframes at 1366 x 768 which is scaled to fit within the viewport via css transform. Resizing the browser triggers on view event even when elements are not in view.
