### ISSUE TITLE
Use offsetWidth/offsetHeight instead of jQuery width()/height() to improve performance

### ISSUE THREAD

**Issue by robertfausk** [protonet/jquery.inview#40]
Another bottleneck of performance is the calculation of the elements width and height via jQuery methods width() and height().

How about using offsetWidth and offsetHeight for getting the elements width and height?

The difference between them is that offsetWidth/offsetHeight includes padding, border and margin.
But the performance would increase drastically.

jQueryApi doc of width: http://api.jquery.com/width/
offset doc: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.offsetWidth

Comparison of performance:
http://jsperf.com/offsetwidth-vs-jquery-width
http://jsperf.com/jquery-css-vs-width-vs-native-width/4

**Comment by tiff** [comment]
thx! fixed with https://github.com/protonet/jquery.inview/commit/e031f5b99fb9dadb406a9a510cd160d204e94f67
