### ISSUE TITLE
Why has visiblepartX and visiblepartY been removed?

### ISSUE THREAD

**Issue by stevebrowndotco** [protonet/jquery.inview#53]
Hi there,

I noticed in this commit you have removed the visible part logic:

https://github.com/protonet/jquery.inview/commit/be2769f8fc9b22587df2bc293b8dd94ef26e0888

What is the reason for this? It was a good feature.

**Comment by tiff** [comment]
Most people didn't use it at all and it had a few bugs. The purpose of this library is to stay as lightweight as possible. You might want to fork and maintain a version where visiblePart is available.
