### ISSUE TITLE
Bower issues

### ISSUE THREAD

**Issue by CHEWX** [protonet/jquery.inview#57]
Hi,

Having issues with Bower that resolves back to this install.

`protonet/jquery.inview=jquery.inview is not a valid repository name`

Not sure if the `/` is valid ?

Thanks,
Tom

**Comment by CHEWX** [comment]
More information:

`bower jquery.inview=jquery.inview#^1.1.2          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/protonet/jquery.inview=jquery.inview.git", exit code of #128 fatal: remote error:    protonet/jquery.inview=jquery.inview is not a valid repository name   Email support@github.com for help`

**Comment by kxhjp09** [comment]
same here.

https://github.com/aterrien/jQuery-Knob/issues/283

it seems '/'  is not valid.
